Updating browser support list and links
WebBluetoothCG/web-bluetooth pull request #515
Opened 2020-09-10 13:02 UTC by Durss

Some links were outdated/dead and some new info were missing, like Apple stating it won't support it (as well as many other APIs) for finger printing reasons, which, i believe, firefox endorsed as well but i couldn't find any official statement. Still, there bug tracker issues are closed as "won't fix".

Bluetooth API doesn't work anymore on Opera or any chromium-based browser but Edge and Chrome on desktop.

Microsoft Edge now supports API properly so i removed a dead status support link and simply saif it's supported

Also added a second iOs "pollyfill app" that's free.

2020-09-10 15:35 UTC, dlech commented on implementation-status.md
> +Supported as of version 56 on desktop, version 84 on mobile.
Does mobile include iOS or just Android?

2020-09-10 15:54 UTC, Durss commented
Sorry for not specifying it !
Mobile only includes android. 
Basically on iOs I believe the only solutions are the 2 apps mentioned above in the readme. I have no iOs device to try but I don't think I'm mistaken.

2020-09-26 01:45 UTC, reillyeon requested changes

2020-09-26 01:45 UTC, reillyeon commented on implementation-status.md
> +Supported as of version 56 on desktop, version 84 on mobile.
Chrome is already covered above and has been shipped on Chrome OS, macOS and Android since Chrome 56 and Windows since Chrome 70. As explained above Linux is implemented behind a flag but unsupported.

2020-09-26 01:45 UTC, reillyeon commented on implementation-status.md
> +Works on android since version 46.
Always capitalize "Android".

2020-09-26 01:45 UTC, reillyeon commented on implementation-status.md
> +Supported but not working on latest versions on desktop :
No spaces before the ":".

2021-10-07 21:48 UTC, MACHONEJ82 approved these changes

2021-10-07 21:48 UTC, MACHONEJ82 commented on implementation-status.md
> -Available behind a flag `opera://flags/#enable-web-bluetooth`.
T

2025-02-08 00:47 UTC, reillyeon approved these changes

2025-02-08 01:07 UTC, merged