Update scanning.bs
WebBluetoothCG/web-bluetooth pull request #520
Opened 2020-09-19 11:33 UTC by motla

Fix #519

2020-09-23 23:50 UTC, reillyeon commented
As required by [CONTRIBUTING.md](https://github.com/WebBluetoothCG/web-bluetooth/blob/master/CONTRIBUTING.md) please join the [Web Bluetooth Community Group](https://www.w3.org/community/web-bluetooth/) so that all the various legal requirements are satisfied.

2020-09-24 06:28 UTC, motla commented
@reillyeon Just done. I missed the contributing.md. Thanks.
For your information I'm working independently on a Bluetooth plugin for Apache Cordova which hopefully will have Bluetooth Mesh capability.
Basic LE and Scanning functions will conform to the Web Bluetooth API, which I'm writing a new JavaScript implementation from scratch, that links user code to native hooks and that I plan to release separately on Github next year. It's really time consuming but at least I get to review the spec.
Tell me if you have plans for Bluetooth Mesh, otherwise I will try to make an API myself.

2020-09-26 01:50 UTC, reillyeon requested changes

2020-09-26 01:50 UTC, reillyeon commented on scanning.bs
> +          <code>|init|.{{BluetoothLEScanFilterInit/services}}.map(service=>{{BluetoothUUID/getService()|BluetoothUUID.getService}}(service))</code>.
Use the language from step 2.5 of [request Bluetooth devices](https://webbluetoothcg.github.io/web-bluetooth/#request-bluetooth-devices) to map BluetoothUUID.getService() over this list.

2020-09-26 02:10 UTC, reillyeon approved these changes

2020-09-26 02:10 UTC, reillyeon commented on scanning.bs
> +          <code>|init|.{{BluetoothLEScanFilterInit/services}}.map(service=>{{BluetoothUUID/getService()|BluetoothUUID.getService}}(service))</code>.
Never mind, I see that we have a note at the bottom of this document explaining how code like this should be interpreted.

2020-09-26 02:11 UTC, merged

2020-09-26 02:13 UTC, reillyeon commented
Are you planning on releasing the Cordova plugin for Android, iOS or both?

We have no current plans to add Bluetooth Mesh-specific features to these specifications but based on past discussions it seems that it should be possible to implement Mesh as a library on top of them, with some issues like MTU negotiation resolved.

2020-09-26 06:48 UTC, motla commented
> Are you planning on releasing the Cordova plugin for Android, iOS or both?

Both platforms (in may work on macOS as well).

Ok thanks for the info. I sure will not dive alone into a JavaScript implementation of the Bluetooth Mesh protocol but probably wrap native Nordic Semiconductor libraries:
- [IOS-nRF-Mesh-Library](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library)
- [Android-nRF-Mesh-Library](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library)

Which will be better for security and responsiveness anyway.

2020-09-26 08:19 UTC, motla commented
https://github.com/WebBluetoothCG/web-bluetooth/pull/520#discussion_r495373656
> Use the language from step 2.5 of request Bluetooth devices to map BluetoothUUID.getService() over this list.

Actually I agree with you. I just copied the syntax I saw previously at `requestLEScan()` definition but didn't see the note at the bottom and I don't think any implementer will.

The user can define `init.service.map()` to anything so better stick to `Array.prototype.map.call(init.service, ...)`.

`options.filters.map()` should be rewritten `Array.prototype.map.call(options.filters, ...)` everywhere as well.

Want me to sumbit another PR on this?

2020-09-28 23:15 UTC, reillyeon commented
Consistency is the most important so if you want to send a PR which updates both instances to reuse the language from the other file I'll approve it.