Update scanning.bs : filter.services can be null
WebBluetoothCG/web-bluetooth pull request #523
Opened 2020-09-19 12:05 UTC by motla

In https://webbluetoothcg.github.io/web-bluetooth/scanning.html#bluetoothlescanfilter-match
As `filter.services` can be null as per the `filter` definition, we should precise it like in the previous steps.

2020-09-26 02:04 UTC, reillyeon requested changes

2020-09-26 02:04 UTC, reillyeon commented on scanning.bs
> +          If <code>|filter|.services</code> is non-<code>null</code>,
It is probably more correct to make `services` non-nullable, as `manufacturerData` and `serviceData` already are. That way this condition vacuously holds if the filter didn't specify any services because there are no UUIDs to check.

2020-09-26 06:37 UTC, motla commented on scanning.bs
> +          If <code>|filter|.services</code> is non-<code>null</code>,
Ok but in this case we have to initialize `services` to an empty array if it's not defined by the user.
https://github.com/WebBluetoothCG/web-bluetooth/blob/acd6ca76694b3ba209af9bd932114afc1c889123/scanning.bs#L415-L417

`, or an empty {{FrozenArray}} otherwise.` ?

2020-09-28 23:16 UTC, reillyeon commented on scanning.bs
> +          If <code>|filter|.services</code> is non-<code>null</code>,
Sounds good to me.

2020-09-29 10:56 UTC, motla commented
Switching to new PR to avoid merge conflict

2020-09-29 10:56 UTC, closed without merging