Remove Bluetooth assigned numbers names
WebBluetoothCG/web-bluetooth pull request #556
Opened 2021-08-13 09:00 UTC by beaufortfrancois

This PR removes Bluetooth assigned numbers names as discussed at https://github.com/WebBluetoothCG/web-bluetooth/issues/535#issuecomment-897660441.

@reillyeon PTAL

2021-08-13 20:06 UTC, reillyeon requested changes

2021-08-13 20:06 UTC, reillyeon commented on index.bs
> +identify services, characteristics, descriptors, and other entities.
Leave a note here explaining why there are separate `getService`, `getCharacteristic` and `getDescriptor` methods even though they now all run the same steps and why that was changed.

2021-08-16 07:47 UTC, beaufortfrancois commented on index.bs
> +identify services, characteristics, descriptors, and other entities.
Done.

2021-08-17 07:06 UTC, beaufortfrancois commented on index.bs
> +identify services, characteristics, descriptors, and other entities.
Does this look good to you?

2021-09-06 12:48 UTC, beaufortfrancois commented
Closing because of https://github.com/WebBluetoothCG/web-bluetooth/pull/560

2021-09-06 12:48 UTC, closed without merging