Permissions Policy integration
WebBluetoothCG/web-bluetooth pull request #582
Opened 2022-04-11 15:20 UTC by gabrielsanbrito

This PR specifies the integration of the Web Bluetooth API with Permissions Policy, so that developers have more control over Bluetooth availability, especially in cross-origin iframe scenarios. 

[Bikeshed preview](https://api.csswg.org/bikeshed/?url=https://github.com/gabrielsanbrito/web-bluetooth/raw/permissions-policy-integration/index.bs)

2022-04-11 23:00 UTC, reillyeon requested changes

2022-04-11 23:00 UTC, reillyeon commented on index.bs
> +    explicitly allow a cross-origin iframe to use the API's methods.
Unlike `[SecureContext]`, each method which will be impacted by Permissions Policy needs to have a step which checks whether the document is allowed to use the feature. See the steps for [`navigator.serial.requestPort()`](https://wicg.github.io/serial/#requestport-method) for an example.

2022-04-13 20:28 UTC, gabrielsanbrito commented on index.bs
> +    explicitly allow a cross-origin iframe to use the API's methods.
I have added the Permissions Policy check step for each of the Bluetooth methods. Also, added the scanning.bs preview link in the PR description.

2022-04-13 20:48 UTC, reillyeon approved these changes

2022-04-13 20:49 UTC, merged

2022-04-13 21:16 UTC, gabrielsanbrito commented
@reillyeon, thank you very much for reviewing this change!