Add manufacturer data blocklist
WebBluetoothCG/web-bluetooth pull request #611
Opened 2023-08-21 22:59 UTC by chengweih001

This is a spec patch to use the manufacturer data block list in https://github.com/WebBluetoothCG/registries/blob/master/manufacturer_data_blocklist.txt.

The spec patch follows how we did for [crrev.com/c/3781118](https://crrev.com/c/3781118).

2023-08-26 01:56 UTC, reillyeon requested changes

2023-08-26 01:56 UTC, reillyeon commented on index.bs
> +the following algorithm:
I'm finding the word "prefix" here is confusing because I don't know what it is a prefix of. What do you think of this alternative wording:

> To **parse an advertising data filter** from a [string](https://infra.spec.whatwg.org/#string) *input*:

Note that I use the "string" concept from the [infra](https://infra.spec.whatwg.org/) spec rather than the ECMA262 string concept, since we are talking about strings in the abstract and not specifically Javascript strings. I also follow the style from that spec and don't explicitly define the type of the result value.

2023-08-26 01:56 UTC, reillyeon commented on index.bs
> +1. Return <code>{dataPrefix: new Uint8Array(|dataArray|), mask: new Uint8Array(|maskArray|)}</code>.
Explicitly build the dictionary, like this:

1. Let *result* be a [new](https://webidl.spec.whatwg.org/#new)  [`BluetoothDataFilterInit`](https://webbluetoothcg.github.io/web-bluetooth/#dictdef-bluetoothdatafilterinit) dictionary.
2. Set *result*["[`dataPrefix`](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothdatafilterinit-dataprefix)"] to...

2023-08-26 01:56 UTC, reillyeon commented on index.bs
> +        with |maskStr| and `16`, or return an error if a {{TypeError}} is thrown.
This can probably be simplified to using infra concepts like checking that *data* is a sequence of [ASCII hex digits](https://infra.spec.whatwg.org/#ascii-hex-digit). It looks like the HTML specification doesn't bother defining exactly how to parse hexadecimal numbers and for example in [Colors](https://html.spec.whatwg.org/#colours) just says to "interpret characters as a hexadecimal number". That's probably good enough.

2023-08-26 01:56 UTC, reillyeon commented on index.bs
> +from Company Identifier Code to an {{Array}} of {{BluetoothDataFilterInit}}, or an error,
Similarly here, use Infra concepts like a [list](https://infra.spec.whatwg.org/#lists) rather than ECMA262 concepts like an Array.

2023-08-28 20:09 UTC, chengweih001 commented on index.bs
> +the following algorithm:
Done.

If we are using infra's string here, for the step of splitting the string |input| , should I avoid using `{{String/split(separator, limit)}}`? Instead write something like this?

```
Let |words| be |input| split on `/`.
```

2023-08-28 20:10 UTC, chengweih001 commented on index.bs
> +1. Return <code>{dataPrefix: new Uint8Array(|dataArray|), mask: new Uint8Array(|maskArray|)}</code>.
Done.

2023-08-28 20:16 UTC, chengweih001 commented on index.bs
> +        with |maskStr| and `16`, or return an error if a {{TypeError}} is thrown.
Done.

2023-08-28 20:17 UTC, chengweih001 commented on index.bs
> +from Company Identifier Code to an {{Array}} of {{BluetoothDataFilterInit}}, or an error,
Done.

2023-08-28 20:25 UTC, reillyeon commented on index.bs
> +the following algorithm:
You can use [strictly split](https://infra.spec.whatwg.org/#strictly-split).

2023-08-28 20:52 UTC, reillyeon requested changes

2023-08-28 20:52 UTC, reillyeon commented on index.bs
> +        , return `false`.
Move this comma to the end of the line above, as otherwise you end up with a space on the left side of the comma.

2023-08-28 20:52 UTC, reillyeon commented on index.bs
> +An advertising data filter is a string that represents a set of manufacturer or
"represents a way to match against manufacturer or service data"

2023-08-28 20:52 UTC, reillyeon commented on index.bs
> +    1. Invoke |result|[{{BluetoothDataFilterInit/dataPrefix}}].{{Array/push()}} with |mask|.
```suggestion
    1. Invoke |result|[{{BluetoothDataFilterInit/mask}}].{{Array/push()}} with |mask|.
```

2023-08-28 20:52 UTC, reillyeon commented on index.bs
> +    1. Invoke |result|[{{BluetoothDataFilterInit/dataPrefix}}].{{Array/push()}} with |mask|.
`push()` isn't defined for `Uint8Array`. Instead I would collect the prefix and mask into lists and then construct the final values from those lists.

2023-08-28 20:52 UTC, reillyeon commented on index.bs
> +1. If the <a>Manufacturer Data blocklist</a>'s value is an error, return `false`.
```suggestion
1. If the <a>Manufacturer Data blocklist</a>'s value is an error, return `blocked`.
```

2023-08-28 22:03 UTC, chengweih001 commented on index.bs
> +the following algorithm:
Done.

2023-08-28 22:03 UTC, chengweih001 commented on index.bs
> +        , return `false`.
Done.

2023-08-28 22:04 UTC, chengweih001 commented on index.bs
> +An advertising data filter is a string that represents a set of manufacturer or
Done.

2023-08-28 22:04 UTC, chengweih001 commented on index.bs
> +    1. Invoke |result|[{{BluetoothDataFilterInit/dataPrefix}}].{{Array/push()}} with |mask|.
Done.

2023-08-28 22:04 UTC, chengweih001 commented on index.bs
> +1. If the <a>Manufacturer Data blocklist</a>'s value is an error, return `false`.
Done.

2023-08-28 22:39 UTC, reillyeon approved these changes

2023-08-28 22:45 UTC, merged