Add WebDriver BiDi extension
WebBluetoothCG/web-bluetooth pull request #622
Opened 2024-03-20 06:58 UTC by OrKoN

2024-03-20 07:01 UTC, OrKoN commented on index.bs
> +```cddl
TODO: turn code blocks into pre with cddl and local/remote cddl classes so that WebDriver BiDi tooling can pick it up

2024-03-20 07:14 UTC, OrKoN commented on index.bs
> +1. Let |id| be the id of |device|.
What is exactly the name/ID of a device? Probably this should link to some definitions from [=Bluetooth device=]

2024-03-28 01:37 UTC, nondebug requested changes

2024-03-28 01:37 UTC, nondebug commented on index.bs
> +The [=remote end steps=] with |command parameters| are:
Let's use indexing syntax since [=command parameters=] is a map:

The [=remote end steps=] with [=command parameters=] |params| are:

1. Let |contextId| be |params|[\`"context"\`].
1. Let |promptId| be |params|[\`"prompt"\`].

2024-03-28 01:37 UTC, nondebug commented on index.bs
> +    1. Dismiss |prompt|.
I think this algorithm should remove |prompt| from [=map of browsing context to device prompts=] once the prompt is acknowledged or dismissed.

2024-03-28 01:37 UTC, nondebug commented on index.bs
> +1. Return a [=map=] matching the <code>bluetooth.RequestDeviceInfo</code> production, with the <code>id</code> field set to |id|, and the <code>name</code> field set to |name|.
nit: [=maps=] are an ordered sequence of entries and don't have fields. How about:

1. Return a [=map=] matching the \<code>bluetooth.RequestDeviceInfo\</code> production, with \`"id"\` set to |id| and \`"name"\` set to |name|.

2024-03-28 07:42 UTC, OrKoN commented on index.bs
> +A <dfn>device prompt</dfn> is a [=tuple=] consisting of a <dfn>device prompt id</dfn> (a string) and a <dfn>set of devices</dfn> (a [=/set=]). It represents a prompt which allows a user to [=prompt t
Made RequestDeviceInfo.name nullable. Updated phrasing.

2024-03-28 08:00 UTC, OrKoN commented
thanks for reviewing @nondebug addressed the comments, PTAL

2024-03-28 09:01 UTC, OrKoN commented on index.bs
> +The bluetooth module contains commands for managing the remote end Bluetooth behavior.
I have removed the definition because it conflicts with another definition with the same id. We also usually do not need the definition for the module, is there a place you want to reference it?

2024-04-05 22:38 UTC, reillyeon requested changes

2024-04-05 22:38 UTC, reillyeon commented on index.bs
> +The bluetooth.RequestDevice is an identifier for a single device in a request device prompt.
```suggestion
A bluetooth.RequestDevice is an identifier for a single device in a request device prompt.
```

2024-04-05 22:38 UTC, reillyeon commented on index.bs
> +The bluetooth.RequestDevicePrompt is an identifier for a single prompt.
```suggestion
A bluetooth.RequestDevicePrompt is an identifier for a single prompt.
```

2024-04-05 22:38 UTC, reillyeon commented on index.bs
> +The bluetooth.RequestDeviceInfo type represents a single device in a request device prompt.
```suggestion
A bluetooth.RequestDeviceInfo represents a single device in a request device prompt.
```

2024-04-05 22:38 UTC, reillyeon commented on index.bs
> +1. If |promptMap|[|browsingContextId|] does not [=map/exist=]::
```suggestion
1. If |promptMap|[|browsingContextId|] does not [=map/exist=]:
```

2024-04-05 22:38 UTC, reillyeon commented on index.bs
> +To <dfn>trigger a prompt open event</dfn> given a [=browsing context=] |context|, a string |promptId|, and a [=/set=] of [=Bluetooth devices=] |devices|:
This is unfortunately unimplementable due to the mismatch between the specification algorithm for "request Bluetooth devices" and how implementations actually have to implement a Bluetooth device selection prompt. As mentioned in #621, the set of Bluetooth devices in the prompt implemented by Chromium is dynamic. This is necessary because Bluetooth device discovery is a gradual process. It is not possible to instantaneously discover all of the nearby available Bluetooth devices.

At best, this could be implemented by waiting for the Bluetooth scan triggered by the appearance of the prompt to time out (usually 30 seconds) before triggering the `requestDevicePromptOpened` event. This would make automated tests quite slow.

The better solution is to introduce an interface similar to the [Chrome DevTools Protocol](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/device_access_handler.cc;l=94;drc=d7d69375c25df2dc3980e6a4edc5d032ec940efc) which generates a new event every time the set of available devices changes. Technically this doesn't require any changes to these steps but requires a note that this event can be fired multiple times for the same prompt ID.

2024-04-06 05:23 UTC, OrKoN commented on index.bs
> +To <dfn>trigger a prompt open event</dfn> given a [=browsing context=] |context|, a string |promptId|, and a [=/set=] of [=Bluetooth devices=] |devices|:
The implementation of this interface will be based on Chrome DevTools Protocol implementation so it will be also emitted multiple times with the updated list of the devices if CDP emits the underlying event multiple times. I could add a note and link #621 because it sounds like the main spec algorithms need to be updated to reflect device list updates. Alternatively, we could add an event called `requestDevicePromptUpdated` to handle updates separately (although I am not sure if the clients really have a use case to distinguish it). Sounds like specifying that event would be completely blocked on #621

2024-04-06 05:25 UTC, OrKoN commented on index.bs
> +
```suggestion

Issue: In practice, the device list is dynamically updated while a prompt is open. The spec text currently does not reflect that but this event might be emitted multiple times with the same `prompt` ID and the fresh device list. See https://github.com/WebBluetoothCG/web-bluetooth/issues/621
```

2024-04-06 05:26 UTC, OrKoN commented on index.bs
> +
@reillyeon Have I described it more or less accurately?

2024-04-09 23:10 UTC, reillyeon commented on index.bs
> +To <dfn>trigger a prompt open event</dfn> given a [=browsing context=] |context|, a string |promptId|, and a [=/set=] of [=Bluetooth devices=] |devices|:
I don't think we need a separate event but we should name it so that developers won't be surprised when it is called more than once. `requestDevicePromptUpdated` seems reasonable with the note you drafted above. Libraries can wrap it in friendler language-specific APIs similar to what Puppeteer has done: https://pptr.dev/api/puppeteer.devicerequestprompt

2024-04-10 17:50 UTC, reillyeon commented on index.bs
> +1. [=Trigger a prompt updated event=] given |browsingContext|, |promptId|, and |scanResult|.
Please add your proposed note about multiple update events here.

2024-04-10 18:24 UTC, OrKoN commented on index.bs
> +1. [=Trigger a prompt updated event=] given |browsingContext|, |promptId|, and |scanResult|.
Done, added the note here.

2024-04-10 22:29 UTC, reillyeon approved these changes

2024-04-10 22:29 UTC, reillyeon commented on index.bs
> +event might be emitted multiple times with the same `prompt` ID and the
```suggestion
event might be emitted multiple times with the same `promptID` and the
```

2024-04-23 15:05 UTC, OrKoN commented
@reillyeon @alexnj @nondebug is there anything blocking us from landing the spec change?

2024-04-23 19:54 UTC, merged