Change BlutoothManufacturerData.data to be tstr
WebBluetoothCG/web-bluetooth pull request #633
Opened 2024-10-07 20:00 UTC by alexnj

This changing [`BluetoothManufacturerData.data` from being a `bstr`](https://github.com/WebBluetoothCG/web-bluetooth/pull/630#discussion_r1783657473) and defining it as a base64 encoded text representation as a `tstr`. Since BiDi is a protocol over JSON, this seems the correct way to represent bytes per [RFC 8610](https://datatracker.ietf.org/doc/html/rfc8610#appendix-E).

2024-10-07 20:07 UTC, reillyeon commented
It seems weird to push how to encode binary data into individual specs. Can we get some guidance from WebDriver BiDi folks on the correct type for this type of argument?

2024-10-07 20:23 UTC, alexnj commented
BiDi spec has [one example](https://w3c.github.io/webdriver-bidi/#type-network-BytesValue) that encodes binary data, and that seems to refer to [forgiving-base64 encode](https://infra.spec.whatwg.org/#forgiving-base64-decode). Not sure if the algorithm would be considered lossy given the code point filtering employed, for transporting `ManufacturerData`. 

/cc @OrKoN

2024-10-08 05:35 UTC, OrKoN commented
Yes, using base64 and a text string is currently recommended for binary data if the size is relatively small and can be inline in a protocol message.

2024-10-08 05:35 UTC, OrKoN approved these changes

2024-10-08 14:16 UTC, OrKoN commented
To clarify, I think referencing the [base64 algorithm](https://infra.spec.whatwg.org/#forgiving-base64) in the infra spec is sufficient as we do not have a central place to handle binary data in the WebDriver BiDi spec. Also from the client and implementation perspective the format is command/event-specific and we do not expect to change/specify it centrally. If we have a better way in the future, we can re-visit but so far I know know of plans to have a better way to deal with large binary files but I do not think a solution for that would be applicable here since CDP also implements this data as base64-encoded strings.

2024-10-08 16:53 UTC, reillyeon requested changes

2024-10-08 16:53 UTC, reillyeon commented on index.bs
> +  <dd>is the [=forgiving-base64 encoded=] result of the manufacturer data [=byte sequence=].</dd>
It feels weird to me to talk about using the forgiving-base64 encode algorithm to encode this data since the browser isn't what is doing the encoding, it is the external script. I think it would make more sense to say that this is "the manufacturer data byte sequence, base64 encoded" and then specify in the algorithm steps which process this command that we use "forgiving-base64 decode" to interpret this externally-provided value.

2024-10-08 17:48 UTC, alexnj commented on index.bs
> +  <dd>is the [=forgiving-base64 encoded=] result of the manufacturer data [=byte sequence=].</dd>
Updated. PTAL.

2024-10-08 18:30 UTC, reillyeon approved these changes

2024-10-09 16:48 UTC, merged